// layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import type { ReactNode } from "react";
import { ThemeProvider } from "next-themes";
import AutoSunsetTheme from "@/components/function/AutoSunsetTheme";

import Header from "@/components/header"
import { Footer } from "@/components/footer";

// 字体：无衬线（正文）— 纤黑/常规/中等
const wenkai = localFont({
  src: [
    { path: "../public/fonts/LXGWWenKai-Light.ttf",   weight: "300", style: "normal" },
    { path: "../public/fonts/LXGWWenKai-Regular.ttf", weight: "400", style: "normal" },
    { path: "../public/fonts/LXGWWenKai-Medium.ttf",  weight: "500", style: "normal" },
  ],
  variable: "--font-wenkai",
  display: "swap",
});

// 字体：等宽（代码）— 纤黑/常规/中等
const wenkaiMono = localFont({
  src: [
    { path: "../public/fonts/LXGWWenKaiMono-Light.ttf",   weight: "300", style: "normal" },
    { path: "../public/fonts/LXGWWenKaiMono-Regular.ttf", weight: "400", style: "normal" },
    { path: "../public/fonts/LXGWWenKaiMono-Medium.ttf",  weight: "500", style: "normal" },
  ],
  variable: "--font-wenkai-mono",
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh" suppressHydrationWarning className={`${wenkai.variable} ${wenkaiMono.variable}`}>
      <body className="min-h-screen cursor-custom font-sans antialiased overflow-x-hidden">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <AutoSunsetTheme />
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
